### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [shiftee/industruino-modbus-converter#1]
In the file "industruino-modbus-converter.ino", you can remove the waiting after the Wire.requestFrom().

These lines can be removed:
```
unsigned timeout = 50;
for(unsigned i=0; i<timeout; i++)
{
	delay(1);
	if( Wire.available() )
		break;
}
```
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

**Comment by shiftee** [comment]
Fixed in https://github.com/shiftee/industruino-modbus-converter/commit/89b2a8764ceed62cb65ad219e9914c50eaaea9ae

Thanks for pointing it out
